version: '3.7'

services:
  hackoort:
    hostname: hackoort
    container_name: hackoort
    image: emsi/hackoort
    build: .
    expose:
      - "22"
      - "5011"
    ports:
    # ssh
    - target: 22
      published: 1122
      protocol: tcp
      mode: host
    # flask
    - target: 5011
      published: 5011
      protocol: tcp
    volumes:
      - ../:/hackoort
    network_mode: "host"