version: '3.7'

services:
  hackoort:
    image: emsi/hackoort${HACKOORT_TAG}
    build:
      context: ./
      dockerfile: Dockerfile

  hackoort-devel:
    hostname: hackoort-devel
    container_name: hackoort-devel
    image: emsi/hackoort-devel${HACKOORT_TAG}
    build:
      context: ./
      dockerfile: Dockerfile-devel
      args:
        HACKOORT_TAG: ${HACKOORT_TAG}
    volumes:
      - ../python/hackoort:/hackoort/hackoort
      - ../python/oortapi:/hackoort/oortapi
      - ../python/oorthap:/hackoort/oorthap
      - ./state:/etc/oort
    network_mode: "host"

  oorthap:
    hostname: oorthap
    container_name: oorthap
    image: emsi/oorthap${HACKOORT_TAG}
    build:
      context: ./
      dockerfile: Dockerfile-oorthap
      args:
        HACKOORT_TAG: ${HACKOORT_TAG}
    volumes:
      - ./state:/etc/oort
    network_mode: "host"
    user: hackoort