version: '3.7'

services:
  hackoort:
    hostname: hackoort
    container_name: hackoort
    image: emsi/hackoort${HACKOORT_TAG}
    build: .
    expose:
      - "22"
      - "5011"
    ports:
    # ssh
    - target: 22
      published: 1122
      protocol: tcp
      mode: host
    # flask
    - target: 5011
      published: 5011
      protocol: tcp
    volumes:
      - ../python/hackoort:/hackoort/hackoort
      - ../python/oortapi:/hackoort/oortapi
      - ../python/oorthap:/hackoort/oorthap
    network_mode: "host"